version: "3.8"

services:
  server:
    # image: 'nginx:stable-alpine'
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - '8000:80'
      # Because we are copyin the stuff in the .dockerfile, we could also leave out volumes - they're still in to override the image for development purposes to reflect any changes immediately
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
  php:
    build: 
      context: .
      dockerfile: dockerfiles/php.dockerfile
      # Because we are copyin the stuff in the .dockerfile, we could also leave out volumes - they're still in to override the image for development purposes to reflect any changes immediately
    volumes:
      - ./src:/var/www/html:delegated
  mysql:
    image: mariadb:10.5.8
    # image: mysql:5.7
    env_file:
      - ./env/mysql.env
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
  artisan:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
  npm:
    image: node:14
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes:
      - ./src:/var/www/html

